### ISSUE TITLE
Angular 6 support

### ISSUE THREAD

**Issue by RoopeHakulinen** [bargreenellingson/ng2-daterange-picker#7]
Thanks for continuing work on this library and fixing it for Angular 5. Greatly appreciated.

This library does not work with Angular 6 though. This is because the Angular 6.0.0 finally dropped animation stuff from the `@angular/core` as stated in the [breaking changes](https://github.com/angular/angular/blob/master/CHANGELOG.md#possible-breaking-changes)):
>*core*: it is no longer possible to import animation-related functions from @angular/core. All animation symbols must now be imported from @angular/animations.

To fix this the animations functions need to be imported from the `@angular/animations`.

**Comment by RoopeHakulinen** [comment]
There's a really simple PR to make this compile also with Angular 6. This is the last issue for our app to be compatible with Angular 6 so would be awesome to get it merged and 1.2.0 released. 

I did not update Angular version in the PR as it should work with Angular 5 and 6 both with the fix for animations import and will not be a breaking change in that sense I guess as `@angular/animations` is a dependency already.

There are duplicate deps in _dependencies_ and _devDependencies_ (e.g. `@angular/cdk` & `@angular/material`) in `package.json` but those aren't that important I guess. 

Let me know if there's anything else I can help with to get this merged.

**Comment by pcvonz** [comment]
I'm going to open up a new issue: to clean up the package.json. Thanks for pointing that out.

**Comment by RoopeHakulinen** [comment]
@pcvonz Thanks for the merge! Any chance of getting a release (even beta) that I could build my project against? :)
