### ISSUE TITLE
Clean up package

### ISSUE THREAD

**Issue by pcvonz** [bargreenellingson/ng2-daterange-picker#9]
from issue #7 

>There are duplicate deps in dependencies and devDependencies (e.g. @angular/cdk & @angular/material) in package.json but those aren't that important I guess.

**Comment by RoopeHakulinen** [comment]
Good job cleaning the `package.json` and thanks for the release! 

I noticed, though, that the _peerDependencies_ for Angular require 6.0.7 or later. Is there some reason why 6.0.0-6.0.6 would not work? :)

**Comment by pcvonz** [comment]
Not at all! I'll edit those when I get back from camping this weekend.
